version: '3.5'

services:
  authorization360_db:
    container_name: authorization360_db
    image: postgres
    env_file: ./.env
    volumes:
      - auth360_pg_data:/var/lib/postgresql/data
    restart: always
    ports:
      - 54321:5432
    networks:
      - auth

  authorization360:
    image: 'vsokoltsov/authorization360'
    container_name: authorization360
    command: bash -c "flask run --host 0.0.0.0"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: ./.env
    volumes:
      - .:/authorization360
    ports:
      - '5000:5000'
    depends_on:
      - authorization360_db
    networks:
      - teamreel
      - auth

volumes:
  auth360_pg_data:

networks:
  teamreel:
    name: teamreel
  auth:
    name: teamreel_auth